# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x10stable.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x04\n\rEventEnvelope\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x16\n\x0eschema_version\x18\x04 \x01(\t\x12\x33\n\x0foccurrence_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0eingestion_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12=\n\x10\x61\x63\x63ount_ingested\x18\n \x01(\x0b\x32!.stable.events.v1.AccountIngestedH\x00\x12\x41\n\x12\x61ssignment_created\x18\x0b \x01(\x0b\x32#.stable.events.v1.AssignmentCreatedH\x00\x12R\n\x1binternal_estimate_generated\x18\x0c \x01(\x0b\x32+.stable.events.v1.InternalEstimateGeneratedH\x00\x12N\n\x19regulated_signal_released\x18\r \x01(\x0b\x32).stable.events.v1.RegulatedSignalReleasedH\x00\x12N\n\x19governance_config_updated\x18\x0e \x01(\x0b\x32).stable.events.v1.GovernanceConfigUpdatedH\x00\x42\t\n\x07payload\"Y\n\x0f\x41\x63\x63ountIngested\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x1b\n\x13outstanding_balance\x18\x02 \x01(\x01\x12\x15\n\rdays_past_due\x18\x03 \x01(\x05\"N\n\x11\x41ssignmentCreated\x12\x15\n\rassignment_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x63\x61_id\x18\x03 \x01(\t\"\x8a\x01\n\x19InternalEstimateGenerated\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x19\n\x11target_account_id\x18\x02 \x01(\t\x12 \n\x18raw_recovery_probability\x18\x03 \x01(\x01\x12\x1e\n\x16\x65stimated_effort_hours\x18\x04 \x01(\x01\"\x7f\n\x17RegulatedSignalReleased\x12\x11\n\tsignal_id\x18\x01 \x01(\t\x12\x1c\n\x14target_assignment_id\x18\x02 \x01(\t\x12\x15\n\rpriority_band\x18\x03 \x01(\t\x12\x1c\n\x14noise_factor_applied\x18\x04 \x01(\x01\"d\n\x17GovernanceConfigUpdated\x12\x11\n\tconfig_id\x18\x01 \x01(\t\x12\x1d\n\x15information_sharpness\x18\x02 \x01(\x01\x12\x17\n\x0fnoise_injection\x18\x03 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTENVELOPE']._serialized_start=68
  _globals['_EVENTENVELOPE']._serialized_end=651
  _globals['_ACCOUNTINGESTED']._serialized_start=653
  _globals['_ACCOUNTINGESTED']._serialized_end=742
  _globals['_ASSIGNMENTCREATED']._serialized_start=744
  _globals['_ASSIGNMENTCREATED']._serialized_end=822
  _globals['_INTERNALESTIMATEGENERATED']._serialized_start=825
  _globals['_INTERNALESTIMATEGENERATED']._serialized_end=963
  _globals['_REGULATEDSIGNALRELEASED']._serialized_start=965
  _globals['_REGULATEDSIGNALRELEASED']._serialized_end=1092
  _globals['_GOVERNANCECONFIGUPDATED']._serialized_start=1094
  _globals['_GOVERNANCECONFIGUPDATED']._serialized_end=1194
# @@protoc_insertion_point(module_scope)
